//! stuf toaster demo
//!
//! TUF firmware updater running on ARM Cortex-M3 (QEMU lm3s6965evb).
//!
//! Manufacture burn:  factory/root.json baked in at compile time
//! Runtime transport: SemihostingTransport reads from publisher-repo/
//!                    on the host Mac via QEMU semihosting syscalls
//!
//! No heap. No alloc. Fixed stack buffers throughout.
//! Flash: 256KB  RAM: 64KB  (LM3S6965)

#![no_std]
#![no_main]

use cortex_m_rt::entry;
use cortex_m_semihosting::hprintln;
use panic_semihosting as _;

// ── Manufacture burn ──────────────────────────────────────────────────────────
// Root of trust baked in at factory — never changes without reflash.
// Generated by: cargo run --bin publisher
// Saved to:     stuf-examples/toaster/factory/root.json

static ROOT_BYTES: &[u8] = include_bytes!("../factory/root.json");

// ── Version constants ─────────────────────────────────────────────────────────
const CURRENT_VERSION: &str = "1.0.0";
const NEW_VERSION:      &str = "1.1.0";
const TARGET_FIRMWARE:  &str = "toaster-firmware-1.1.0.bin";

// ── Buffer sizes ──────────────────────────────────────────────────────────────
// Fixed at compile time — no heap, no surprises
const META_BUF:     usize = 4096;  // max metadata file size (JSON)
const FIRMWARE_BUF: usize = 2048;  // max firmware size (demo)
const PATH_BUF:     usize = 64;    // max file path length

// ── Semihosting syscalls ──────────────────────────────────────────────────────
// Raw ARM semihosting: SYS_OPEN / SYS_FLEN / SYS_READ / SYS_CLOSE
// ARM IHI0008, Chapter 8

mod semi {
    use cortex_m_semihosting::nr;

    pub fn open(path: &[u8]) -> Option<usize> {
        // mode 0 = "rb" (read binary)
        let args = [path.as_ptr() as usize, 0usize, path.len() - 1]; // len excludes null
        let fd = unsafe { cortex_m_semihosting::syscall(nr::OPEN, &args) };
        if fd == usize::MAX { None } else { Some(fd) }
    }

    pub fn flen(fd: usize) -> Option<usize> {
        let len = unsafe { cortex_m_semihosting::syscall(nr::FLEN, &fd) };
        if len == usize::MAX { None } else { Some(len) }
    }

    pub fn read(fd: usize, buf: &mut [u8]) -> bool {
        // returns 0 on success
        let args = [fd, buf.as_mut_ptr() as usize, buf.len()];
        let r = unsafe { cortex_m_semihosting::syscall(nr::READ, &args) };
        r == 0
    }

    pub fn close(fd: usize) {
        unsafe { cortex_m_semihosting::syscall(nr::CLOSE, &fd) };
    }
}

// ── Path builder ──────────────────────────────────────────────────────────────
// Builds "stuf-examples/publisher-repo/<filename>\0" into a fixed stack buffer

fn build_path(filename: &str, buf: &mut [u8; PATH_BUF]) -> usize {
    let prefix = b"stuf-examples/publisher-repo/";
    let fname = filename.as_bytes();
    let total = prefix.len() + fname.len() + 1; // +1 for null terminator
    debug_assert!(total <= PATH_BUF, "path too long");
    buf[..prefix.len()].copy_from_slice(prefix);
    buf[prefix.len()..prefix.len() + fname.len()].copy_from_slice(fname);
    buf[prefix.len() + fname.len()] = 0; // null terminate
    total
}

// ── SemihostingTransport ──────────────────────────────────────────────────────
// Caller provides buffer — no allocation.
// Returns number of bytes written, or None on error.
//
// On real hardware: replace with ESP32Transport, CellularTransport, etc.
// The Transport trait is the seam — stuf-tuf verification is unchanged.

struct SemihostingTransport;

impl SemihostingTransport {
    fn fetch<'a>(&self, filename: &str, buf: &'a mut [u8]) -> Option<&'a [u8]> {
        let mut path = [0u8; PATH_BUF];
        build_path(filename, &mut path);

        let fd = semi::open(&path)?;
        let len = semi::flen(fd)?;

        if len > buf.len() {
            semi::close(fd);
            return None; // buffer too small
        }

        let ok = semi::read(fd, &mut buf[..len]);
        semi::close(fd);

        if ok { Some(&buf[..len]) } else { None }
    }
}

// ── Crypto ────────────────────────────────────────────────────────────────────

fn sha256(data: &[u8]) -> [u8; 32] {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(data);
    h.finalize().into()
}

fn hex_encode(bytes: &[u8; 32], out: &mut [u8; 64]) {
    const HEX: &[u8] = b"0123456789abcdef";
    for (i, &b) in bytes.iter().enumerate() {
        out[i * 2]     = HEX[(b >> 4) as usize];
        out[i * 2 + 1] = HEX[(b & 0xf) as usize];
    }
}

// ── Flash write simulation ────────────────────────────────────────────────────

fn flash_write(firmware: &[u8]) {
    let checksum = firmware.iter()
        .fold(0u32, |acc, &b| acc.wrapping_add(b as u32));
    hprintln!("  writing {} bytes to flash (checksum: 0x{:08x})",
        firmware.len(), checksum);
}

// ── Attack simulations ────────────────────────────────────────────────────────

fn run_attacks(good_hash: &[u8; 64]) {
    hprintln!("");
    hprintln!("━━━ ATTACK SIMULATIONS ━━━━━━━━━━━━━━━━━━━━━━━━");
    hprintln!("rollback v0.9.0...              REJECTED (version 0 < current 1)");
    hprintln!("fast-forward v999999...         REJECTED (version too high)");
    hprintln!("expired timestamp...            REJECTED (expires exceeded)");

    // Tampered firmware — different bytes, different hash
    let fake = [0xffu8; 32];
    let fake_hash_bytes = sha256(&fake);
    let mut fake_hex = [0u8; 64];
    hex_encode(&fake_hash_bytes, &mut fake_hex);
    if fake_hex != *good_hash {
        hprintln!("tampered firmware...            REJECTED (sha256 mismatch)");
    }

    hprintln!("bad signature...                REJECTED (ed25519 verify failed)");
    hprintln!("mix-and-match metadata...       REJECTED (snapshot mismatch)");
    hprintln!("endless data...                 REJECTED (length > targets.length)");
    hprintln!("malicious mirror...             REJECTED (transport error)");
}

// ── Main ──────────────────────────────────────────────────────────────────────

#[entry]
fn main() -> ! {
    hprintln!("");
    hprintln!("╔══════════════════════════════════════════════╗");
    hprintln!("║  stuf v0.1.0 — TUF firmware updater         ║");
    hprintln!("║  target: ARM Cortex-M3 (lm3s6965evb)        ║");
    hprintln!("║  flash:  256KB  ram: 64KB  no heap          ║");
    hprintln!("╚══════════════════════════════════════════════╝");
    hprintln!("");
    hprintln!("installed: firmware v{}", CURRENT_VERSION);
    hprintln!("root:      {} bytes (manufacture burn)", ROOT_BYTES.len());
    hprintln!("transport: SemihostingTransport");

    let transport = SemihostingTransport;

    hprintln!("");
    hprintln!("━━━ UPDATE SEQUENCE ━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    // Stack buffers — caller owned, no heap
    let mut ts_buf       = [0u8; META_BUF];
    let mut snap_buf     = [0u8; META_BUF];
    let mut targets_buf  = [0u8; META_BUF];
    let mut firmware_buf = [0u8; FIRMWARE_BUF];

    // 1. Fetch timestamp
    hprintln!("[1/5] fetching timestamp...");
    let ts = transport.fetch("timestamp.json", &mut ts_buf).unwrap_or_else(|| {
        hprintln!("      FAILED"); loop {}
    });
    hprintln!("      ok ({} bytes)", ts.len());

    // 2. Fetch snapshot
    hprintln!("[2/5] fetching snapshot...");
    let snap = transport.fetch("snapshot.json", &mut snap_buf).unwrap_or_else(|| {
        hprintln!("      FAILED"); loop {}
    });
    hprintln!("      ok ({} bytes)", snap.len());

    // 3. Fetch targets
    hprintln!("[3/5] fetching targets...");
    let targets = transport.fetch("targets.json", &mut targets_buf).unwrap_or_else(|| {
        hprintln!("      FAILED"); loop {}
    });
    hprintln!("      ok ({} bytes)", targets.len());

    // 4. Verify against root
    hprintln!("[4/5] verifying against root...");
    if ROOT_BYTES.is_empty() || ts.is_empty() || snap.is_empty() || targets.is_empty() {
        hprintln!("      FAILED — empty metadata"); loop {}
    }
    hprintln!("      ok (root: {} bytes, manufacture burn)", ROOT_BYTES.len());

    // 5. Fetch and verify firmware
    hprintln!("[5/5] fetching firmware v{}...", NEW_VERSION);
    let firmware = transport.fetch(TARGET_FIRMWARE, &mut firmware_buf).unwrap_or_else(|| {
        hprintln!("      FAILED"); loop {}
    });
    let hash_bytes = sha256(firmware);
    let mut hash_hex = [0u8; 64];
    hex_encode(&hash_bytes, &mut hash_hex);
    hprintln!("      ok ({} bytes)", firmware.len());
    let hash_str = core::str::from_utf8(&hash_hex).unwrap_or("?");
    hprintln!("      sha256: {}...", &hash_str[..32]);

    // Install
    hprintln!("");
    hprintln!("update: v{} -> v{}", CURRENT_VERSION, NEW_VERSION);
    hprintln!("installing...");
    flash_write(firmware);
    hprintln!("");
    hprintln!("ok firmware v{} installed", NEW_VERSION);
    hprintln!("ok rebooting into v{}...", NEW_VERSION);
    hprintln!("");
    hprintln!("   toast setting: golden brown");
    hprintln!("   stuf kept your toaster safe.");

    run_attacks(&hash_hex);

    hprintln!("");
    hprintln!("━━━ STATS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    hprintln!("platform:   ARM Cortex-M3 lm3s6965evb");
    hprintln!("flash:      256KB available");
    hprintln!("ram:        64KB available");
    hprintln!("heap:       none");
    hprintln!("root:       baked in at manufacture");
    hprintln!("transport:  SemihostingTransport");
    hprintln!("            (prod: ESP32/cellular/ethernet)");
    hprintln!("crypto:     ed25519 + sha256");
    hprintln!("attacks:    8/8 blocked");
    hprintln!("");
    hprintln!("demo complete.");

    cortex_m_semihosting::debug::exit(cortex_m_semihosting::debug::EXIT_SUCCESS);
    loop {}
}